# ───────────────────────────────────────────────────────────
# netlify.toml (at repo root)
# ───────────────────────────────────────────────────────────

[build]
  command = "middleman build"
  publish = "build"
  environment = {NODE_ENV = "production", NETLIFY_IMAGE_CDN = "true"}

[dev]
  # command to run your Middleman server in live-reload mode
  command = "foreman start"
  port    = 3000        # port Middleman opens by default
  targetPort = 4567     # netlify-dev proxies to 8888

# ───────────────────────────────────────────────────────────
# 1) Fingerprinted images (long cache, immutable)
# ───────────────────────────────────────────────────────────
[[headers]]
  for = "/images/*.avif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/uploads/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# ───────────────────────────────────────────────────────────
# 2) Fingerprinted JS & CSS (long cache, immutable)
# ───────────────────────────────────────────────────────────
[[headers]]
  for = "/javascripts/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/stylesheets/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# ───────────────────────────────────────────────────────────
# 3) Non-fingerprinted JSON/XML or config files
#    – short cache, must revalidate
# ───────────────────────────────────────────────────────────
[[headers]]
  for = "/admin/config.yml"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.xml"
  [headers.values]
    Cache-Control = "public, max-age=300, must-revalidate"

[[headers]]
  for = "/*.json"
  [headers.values]
    Cache-Control = "public, max-age=300, must-revalidate"

# ───────────────────────────────────────────────────────────
# 4) HTML pages (root & all subdirectories)
#    – short cache to enable prefetching but still revalidate
# ───────────────────────────────────────────────────────────
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=60, must-revalidate"

# ───────────────────────────────────────────────────────────
# 5) Redirect any unmatched route to 404
# ───────────────────────────────────────────────────────────
[[redirects]]
  from   = "*"
  to     = "/404"
  status = 404
