# ───────────────────────────────────────────────────────────
# netlify.toml (at repo root)
# ───────────────────────────────────────────────────────────

[build]
  command = "middleman build"
  publish = "build"
  environment = {NODE_ENV = "production", NETLIFY_IMAGE_CDN = "true"}

# [dev]
#   # command to run your Middleman server in live-reload mode
#   command = "foreman start"
#   port    = 3000        # port Middleman opens by default
#   targetPort = 4567     # netlify-dev proxies to 8888
