# ───────────────────────────────────────────────────────────
# netlify.toml (at repo root)
# ───────────────────────────────────────────────────────────
[build]
  command = "middleman build"
  publish = "build"
  environment = {NODE_ENV = "production", NETLIFY_IMAGE_CDN = "true"}
[dev]
  # command to run your Middleman server in live-reload mode
  command = "foreman start"
  port    = 3000        # port Middleman opens by default
  targetPort = 4567     # netlify-dev proxies to 8888

# ───────────────────────────────────────────────────────────
# 1) HTML pages (root & all subdirectories) - FIRST PRIORITY
#    – short cache to enable prefetching but still revalidate
# ───────────────────────────────────────────────────────────
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=10, must-revalidate"

# ───────────────────────────────────────────────────────────
# 2) Fingerprinted images (long cache, immutable)
# ───────────────────────────────────────────────────────────
[[headers]]
  for = "**/*.avif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "**/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "**/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "**/*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "**/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "**/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# ───────────────────────────────────────────────────────────
# 3) Fingerprinted JS & CSS anywhere (long cache, immutable)
# ───────────────────────────────────────────────────────────
[[headers]]
  for = "**/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "**/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# ───────────────────────────────────────────────────────────
# 4) Font files anywhere (long cache, immutable)
# ───────────────────────────────────────────────────────────
[[headers]]
  for = "**/*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "**/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "**/*.ttf"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "**/*.otf"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# ───────────────────────────────────────────────────────────
# 5) Non-fingerprinted JSON/XML or config files
#    – short cache, must revalidate
# ───────────────────────────────────────────────────────────

[[headers]]
  for = "**/*.yml"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "**/*.json"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# ───────────────────────────────────────────────────────────
# 6) SEO and Security Headers
# ───────────────────────────────────────────────────────────
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# ───────────────────────────────────────────────────────────
# 7) Redirect any unmatched route to 404
# ───────────────────────────────────────────────────────────
[[redirects]]
  from   = "*"
  to     = "/404"
  status = 404
